name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: latest
  
    - name: Clean install (remove lockfile and node_modules)
      run: |
        rm -rf node_modules package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
